# 主库数据源配置
spring.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.master.url=${SPRING_DATASOURCE_MASTER_URL:jdbc:mysql://localhost:3307/seckill?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
spring.datasource.master.username=${SPRING_DATASOURCE_MASTER_USERNAME:root}
spring.datasource.master.password=${SPRING_DATASOURCE_MASTER_PASSWORD:123456}

# 从库数据源配置
spring.datasource.slave.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.slave.url=${SPRING_DATASOURCE_SLAVE_URL:jdbc:mysql://localhost:3308/seckill?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
spring.datasource.slave.username=${SPRING_DATASOURCE_SLAVE_USERNAME:root}
spring.datasource.slave.password=${SPRING_DATASOURCE_SLAVE_PASSWORD:123456}

# MyBatis 配置
mybatis.type-aliases-package=com.example.seckill_demo.entity
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml

# 服务端口
server.port=8080

# 日志配置
logging.level.org.springframework.jdbc.datasource=INFO
logging.level.com.example.seckill_demo=INFO

# Redis配置
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=
spring.data.redis.database=0

# 监控配置
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always